// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBhfhYjmDbHz9q3bak4x5cd47p1aHtUI',
    appId: '1:799021501816:web:271a33ef1ec34810a78c8d',
    messagingSenderId: '799021501816',
    projectId: 'root-adset-helper',
    authDomain: 'root-adset-helper.firebaseapp.com',
    storageBucket: 'root-adset-helper.appspot.com',
    measurementId: 'G-JE1X4FHR28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo2DJB6OjeITkDRm3aO_BEHpBxTRsWUJc',
    appId: '1:799021501816:android:4578b63ef564ba1aa78c8d',
    messagingSenderId: '799021501816',
    projectId: 'root-adset-helper',
    storageBucket: 'root-adset-helper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwlw-g8vzQmt70T_0Kxy0Ev351weD6B0',
    appId: '1:799021501816:ios:69884100ed9e02eea78c8d',
    messagingSenderId: '799021501816',
    projectId: 'root-adset-helper',
    storageBucket: 'root-adset-helper.appspot.com',
    iosClientId:
        '799021501816-vrftclgssav989atitt2g4uemfpko586.apps.googleusercontent.com',
    iosBundleId: 'com.example.rootAdsetHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlwlw-g8vzQmt70T_0Kxy0Ev351weD6B0',
    appId: '1:799021501816:ios:15e47e37c1358a93a78c8d',
    messagingSenderId: '799021501816',
    projectId: 'root-adset-helper',
    storageBucket: 'root-adset-helper.appspot.com',
    iosClientId:
        '799021501816-on552fbd895t92cdpujsnugrnv3nqofd.apps.googleusercontent.com',
    iosBundleId: 'com.example.rootAdsetHelper.RunnerTests',
  );
}
